# GitLab CI Runner configuration file
# By Thanh Nguyen <btnguyen2k@gmail.com>

cache:

variables:
  APP_ROOT: ./src/github.com/btnguyen2k/goff-id

before_script:
  - whoami && pwd && date
  - "export CI_PROJECT_VERSION=`echo $CI_COMMIT_REF_NAME | cut -d'-' -f 2`"
  - "echo CI_PROJECT_VERSION: $CI_COMMIT_REF_NAME --\\> $CI_PROJECT_VERSION"
  - "export GOPATH=`pwd`"
  - "export APP_ROOT=$GOPATH/$APP_ROOT"
  - "echo APP_ROOT: $APP_ROOT"

after_script:

stages:
  - build
  - test
  - docker-build
  - docker-release

build:
  stage: build
  script:
    - date
    - cd $APP_ROOT && dep ensure && go build server.go
  tags:
    - gitlabci-build
    - golang

test:
  stage: test
  only:
    # Run ony if commit has tag release-x.y.z.t, staging-x.y.z.t, or test-x.y.z.t
    - /^release-.*$/
    - /^staging-.*$/
    - /^test-.*$/
  script:
    - date
    - cd $APP_ROOT && dep ensure && go test -v -count=1
  tags:
    - gitlabci-build
    - golang

build docker image:
  stage: docker-build
  only:
    - /^release-.*$/
    - /^staging-.*$/
    - /^test-.*$/
  script:
    - date
    - cd $APP_ROOT && dep ensure && go build server.go
    - cd $APP_ROOT && docker build --force-rm --squash -t $DOCKER_REGISTRY_SERVER_WITH_NAMESPACE/$CI_PROJECT_NAME:$CI_PROJECT_VERSION .
    - docker rmi $(docker images -f "dangling=true" -q)
  tags:
    - gitlabci-build
    - golang

push test to docker registry:
  stage: docker-release
  only:
    - /^test-.*$/
  script:
    - date
    - docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD $DOCKER_REGISTRY_SERVER
    - docker tag $DOCKER_REGISTRY_SERVER_WITH_NAMESPACE/$CI_PROJECT_NAME:$CI_PROJECT_VERSION $DOCKER_REGISTRY_SERVER_WITH_NAMESPACE/$CI_PROJECT_NAME:$CI_PROJECT_VERSION-test
    - docker push $DOCKER_REGISTRY_SERVER_WITH_NAMESPACE/$CI_PROJECT_NAME:$CI_PROJECT_VERSION-test
  tags:
    - gitlabci-build
    - golang
  when: manual

push staging to docker registry:
  stage: docker-release
  only:
    - /^staging-.*$/
  script:
    - date
    - docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD $DOCKER_REGISTRY_SERVER
    - docker tag $DOCKER_REGISTRY_SERVER_WITH_NAMESPACE/$CI_PROJECT_NAME:$CI_PROJECT_VERSION $DOCKER_REGISTRY_SERVER_WITH_NAMESPACE/$CI_PROJECT_NAME:$CI_PROJECT_VERSION-staging
    - docker push $DOCKER_REGISTRY_SERVER_WITH_NAMESPACE/$CI_PROJECT_NAME:$CI_PROJECT_VERSION-test
  tags:
    - gitlabci-build
    - golang
  when: manual

push release to docker registry:
  stage: docker-release
  only:
    - /^release-.*$/
  script:
    - date
    - docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD $DOCKER_REGISTRY_SERVER
    - docker tag $DOCKER_REGISTRY_SERVER_WITH_NAMESPACE/$CI_PROJECT_NAME:$CI_PROJECT_VERSION $DOCKER_REGISTRY_SERVER_WITH_NAMESPACE/$CI_PROJECT_NAME:latest
    - docker push $DOCKER_REGISTRY_SERVER_WITH_NAMESPACE/$CI_PROJECT_NAME:$CI_PROJECT_VERSION
    - docker push $DOCKER_REGISTRY_SERVER_WITH_NAMESPACE/$CI_PROJECT_NAME:latest
  tags:
    - gitlabci-build
    - golang
  when: manual
